FROM openjdk:21
EXPOSE 8080
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
COPY /src/main/resources/application-prod.yml /application-prod.yml
ENV TZ Asia/Seoul
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "-Dspring.config.location=classpath:/application-prod.yml", "/app.jar"]